version: "3.1"
services:
  mojaPostgresBaza:
    image: "jurerelja/or-fer"
    container_name: mojaPostgresBaza
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5435:5432"
